controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - RightBack_wheel
      - RightMid_wheel
      - RightFront_wheel
      - LeftBack_wheel
      - LeftMid_wheel
      - LeftFront_wheel
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
